syntax = "proto3";
package messages;

/// user platform which login the system
enum PlatformType {
  Desktop = 0;
  Mobile = 1;
}

/// message content type
enum ContentType {
  Default = 0;
  Text = 1;
  Image = 2;
  Video = 3;
  Audio = 4;
  File = 5;
  Emoji = 6;
  VideoCall = 7;
  AudioCall = 8;
  Error = 9;
}

enum MsgType {
  MsgTypeSingleMsg = 0;

  MsgTypeGroupMsg = 1;

  /// group operation
  MsgTypeGroupInvitation = 2;
  MsgTypeGroupInviteNew = 3;
  MsgTypeGroupMemberExit = 4;
  MsgTypeGroupRemoveMember = 5;
  MsgTypeGroupDismiss = 6;
  MsgTypeGroupDismissOrExitReceived = 7;
  MsgTypeGroupInvitationReceived = 8;
  MsgTypeGroupUpdate = 9;

  /// friend operation
  MsgTypeFriendApplyReq = 10;
  MsgTypeFriendApplyResp = 11;
  MsgTypeFriendBlack = 12;
  MsgTypeFriendDelete = 13;

  /// single call operation
  MsgTypeSingleCallInvite = 14;
  MsgTypeRejectSingleCall = 15;
  MsgTypeAgreeSingleCall = 16;
  MsgTypeSingleCallInviteNotAnswer = 17;
  MsgTypeSingleCallInviteCancel = 18;
  MsgTypeSingleCallOffer = 19;
  MsgTypeHangup = 20;
  MsgTypeConnectSingleCall = 21;
  MsgTypeCandidate = 22;

  MsgTypeRead = 23;
  MsgTypeMsgRecResp = 24;
  MsgTypeNotification = 25;
  MsgTypeService = 26;
  MsgTypeFriendshipReceived = 27;
}

/// decode message content by content type
/// the content is candidate, when message type is Candidate
/// the content is sustain, when message type is Hangup
/// the content is String::to_vec(), when message type is SingleMsg/GroupMsg
/// other message type, the content is bincode::serialize(&T)
message Msg {
  // must have
  string send_id = 1;
  // must have
  string receiver_id = 2;
  // must have
  string local_id = 3;
  string server_id = 4;
  // timestamp
  int64 create_time = 5;
  int64 send_time = 6;

  // receiver sequence
  int64 seq = 7;
  MsgType msg_type = 8;
  ContentType content_type = 9;
  bytes content = 10;
  bool is_read = 11;

  string group_id = 15;

  // platform of the sender
  PlatformType platform = 16;

  // user avatar
  string avatar = 17;
  // user nickname
  string nickname = 18;

  // related message id
  optional string related_msg_id = 19;

  /// send sequence
  int64 send_seq = 20;
}

message MsgRead {
  repeated int64 msg_seq = 1;
  string user_id = 2;
}

message MsgReadReq { MsgRead msg_read = 1; }

message MsgReadResp {}

message Candidate {
  string candidate = 1;
  optional string sdp_mid = 2;
  optional int32 sdp_m_index = 3;
}

enum SingleCallInviteType {
  SingleAudio = 0;
  SingleVideo = 1;
}

message AgreeSingleCall { string sdp = 1; }

message SingleCallInvite { SingleCallInviteType invite_type = 1; }

message SingleCallInviteAnswer {
  bool agree = 1;
  SingleCallInviteType invite_type = 2;
}

message SingleCallInviteNotAnswer { SingleCallInviteType invite_type = 1; }

message SingleCallInviteCancel { SingleCallInviteType invite_type = 2; }

message SingleCallOffer { string sdp = 1; }

message Hangup {
  SingleCallInviteType invite_type = 1;
  int64 sustain = 2;
}

/// user and group id
message UserAndGroupID {
  string user_id = 1;
  string group_id = 2;
}

message GroupInviteNew {
  string user_id = 1;
  string group_id = 2;
  repeated string members = 3;
}

message SendMsgRequest { Msg message = 1; }

message SendGroupMsgRequest {
  Msg message = 1;
  repeated GroupMemSeq members = 2;
}

message MsgResponse {
  string local_id = 1;
  string server_id = 2;
  int64 send_time = 3;
  string err = 4;
}

message GroupMemSeq {
  string mem_id = 1;
  int64 cur_seq = 2;
  int64 max_seq = 3;
  bool need_update = 4;
}

service MsgService {
  // send message through rpc
  rpc SendMessage(SendMsgRequest) returns (MsgResponse);
  // send single message to user by websocket
  rpc SendMsgToUser(SendMsgRequest) returns (MsgResponse);
  // send group message to user by websocket
  rpc SendGroupMsgToUser(SendGroupMsgRequest) returns (MsgResponse);
}

/// chat service, receive message then generate message id and send message to
/// mq; response operation result;
service ChatService { rpc SendMsg(SendMsgRequest) returns (MsgResponse); }
