drop table if exists users;
CREATE TABLE "public"."users"
(
    "id"               varchar(36)    NOT NULL,
    "username"         varchar(36),
    "email"            varchar(100),
    "password"         varchar(128)   NOT NULL,
    "nickname"         varchar(50),
    "avatar_url"       varchar(255),
    "created_at"       timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"       timestamptz(6),
    "phone"            varchar(36)    NOT NULL,
    "address"          varchar(255),
    "head_image"       varchar(255),
    "head_image_thumb" varchar(255),
    "sex"              int4,
    "user_stat"        int4                    DEFAULT 1,
    "tenant_id"        varchar(20),
    "last_login_time"  timestamptz(6),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."users"
    OWNER TO "postgres";
COMMENT
    ON COLUMN "public"."users"."id" IS '用户ID';
COMMENT
    ON COLUMN "public"."users"."username" IS '用户名';
COMMENT
    ON COLUMN "public"."users"."email" IS '邮箱';
COMMENT
    ON COLUMN "public"."users"."password" IS '密码';
COMMENT
    ON COLUMN "public"."users"."nickname" IS '昵称';
COMMENT
    ON COLUMN "public"."users"."created_at" IS '创建时间';
COMMENT
    ON COLUMN "public"."users"."updated_at" IS '修改时间';
COMMENT
    ON COLUMN "public"."users"."phone" IS '手机号';
COMMENT
    ON COLUMN "public"."users"."address" IS '地址';
COMMENT
    ON COLUMN "public"."users"."head_image" IS '用户头像';
COMMENT
    ON COLUMN "public"."users"."head_image_thumb" IS '用户头像缩略图';
COMMENT
    ON COLUMN "public"."users"."sex" IS '性别 1:男 2:女';
COMMENT
    ON COLUMN "public"."users"."user_stat" IS '用户状态(1-正常，2-已删除 3-已注销)';
COMMENT
    ON COLUMN "public"."users"."tenant_id" IS '企业号';
COMMENT
    ON COLUMN "public"."users"."last_login_time" IS '最后登录时间';
COMMENT
    ON TABLE "public"."users" IS '用户表';

drop table if exists user_config;
CREATE TABLE "public"."user_config"
(
    "id"                 int4 GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    "user_id"            varchar(36)                                                                        NOT NULL,
    "allow_phone_search" int4           DEFAULT 2,
    "allow_id_search"    int4           DEFAULT 2,
    "auto_load_video"    int4           DEFAULT 2,
    "auto_load_pic"      int4           DEFAULT 2,
    "msg_read_flag"      int4           DEFAULT 2,
    "create_time"        timestamptz(6) DEFAULT CURRENT_TIMESTAMP,
    "update_time"        timestamptz(6)
);
ALTER TABLE "public"."user_config"
    OWNER TO "postgres";
COMMENT
    ON COLUMN "public"."user_config"."id" IS '主键';
COMMENT
    ON COLUMN "public"."user_config"."user_id" IS '用户ID';
COMMENT
    ON COLUMN "public"."user_config"."allow_phone_search" IS '是否允许手机搜索(1-是，2-否)';
COMMENT
    ON COLUMN "public"."user_config"."allow_id_search" IS '是否允许ID搜索(1-是，2-否)';
COMMENT
    ON COLUMN "public"."user_config"."auto_load_video" IS '是否自动缓存视频(1-是，2-否)';
COMMENT
    ON COLUMN "public"."user_config"."auto_load_pic" IS '是否自动加载图片(1-是，2-否)';
COMMENT
    ON COLUMN "public"."user_config"."msg_read_flag" IS '是否已读回执(1-是，2-否)';
COMMENT
    ON COLUMN "public"."user_config"."create_time" IS '创建时间';
COMMENT
    ON COLUMN "public"."user_config"."update_time" IS '修改时间';
COMMENT
    ON TABLE "public"."user_config" IS '用户设置表';
