----------------------------250512  Start----------------------------
drop table if exists users;
CREATE TABLE "public"."users"
(
    "id"               varchar(36)    NOT NULL,
    "username"         varchar(36),
    "email"            varchar(100),
    "password"         varchar(128)   NOT NULL,
    "nickname"         varchar(50),
    "avatar_url"       varchar(255),
    "created_at"       timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"       timestamptz(6),
    "phone"            varchar(36)    NOT NULL,
    "address"          varchar(255),
    "head_image"       varchar(255),
    "head_image_thumb" varchar(255),
    "sex"              int4,
    "user_stat"        int4                    DEFAULT 1,
    "tenant_id"        varchar(20),
    "last_login_time"  timestamptz(6),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."users"
    OWNER TO "postgres";
COMMENT
ON COLUMN "public"."users"."id" IS '用户ID';
COMMENT
ON COLUMN "public"."users"."username" IS '用户名';
COMMENT
ON COLUMN "public"."users"."email" IS '邮箱';
COMMENT
ON COLUMN "public"."users"."password" IS '密码';
COMMENT
ON COLUMN "public"."users"."nickname" IS '昵称';
COMMENT
ON COLUMN "public"."users"."created_at" IS '创建时间';
COMMENT
ON COLUMN "public"."users"."updated_at" IS '修改时间';
COMMENT
ON COLUMN "public"."users"."phone" IS '手机号';
COMMENT
ON COLUMN "public"."users"."address" IS '地址';
COMMENT
ON COLUMN "public"."users"."head_image" IS '用户头像';
COMMENT
ON COLUMN "public"."users"."head_image_thumb" IS '用户头像缩略图';
COMMENT
ON COLUMN "public"."users"."sex" IS '性别 1:男 2:女';
COMMENT
ON COLUMN "public"."users"."user_stat" IS '用户状态(1-正常，2-已删除 3-已注销)';
COMMENT
ON COLUMN "public"."users"."tenant_id" IS '企业号';
COMMENT
ON COLUMN "public"."users"."last_login_time" IS '最后登录时间';
COMMENT
ON TABLE "public"."users" IS '用户表';

drop table if exists user_config;
CREATE TABLE "public"."user_config"
(
    "id"                 int4 GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    "user_id"            varchar(36)                                                                        NOT NULL,
    "allow_phone_search" int4           DEFAULT 2,
    "allow_id_search"    int4           DEFAULT 2,
    "auto_load_video"    int4           DEFAULT 2,
    "auto_load_pic"      int4           DEFAULT 2,
    "msg_read_flag"      int4           DEFAULT 2,
    "create_time"        timestamptz(6) DEFAULT CURRENT_TIMESTAMP,
    "update_time"        timestamptz(6)
);
ALTER TABLE "public"."user_config"
    OWNER TO "postgres";
COMMENT
ON COLUMN "public"."user_config"."id" IS '主键';
COMMENT
ON COLUMN "public"."user_config"."user_id" IS '用户ID';
COMMENT
ON COLUMN "public"."user_config"."allow_phone_search" IS '是否允许手机搜索(1-是，2-否)';
COMMENT
ON COLUMN "public"."user_config"."allow_id_search" IS '是否允许ID搜索(1-是，2-否)';
COMMENT
ON COLUMN "public"."user_config"."auto_load_video" IS '是否自动缓存视频(1-是，2-否)';
COMMENT
ON COLUMN "public"."user_config"."auto_load_pic" IS '是否自动加载图片(1-是，2-否)';
COMMENT
ON COLUMN "public"."user_config"."msg_read_flag" IS '是否已读回执(1-是，2-否)';
COMMENT
ON COLUMN "public"."user_config"."create_time" IS '创建时间';
COMMENT
ON COLUMN "public"."user_config"."update_time" IS '修改时间';
COMMENT
ON TABLE "public"."user_config" IS '用户设置表';
----------------------------250512  End------------------------------
----------------------------250516  Start----------------------------
-- 双向好友关系表 (每个关系存储两条记录)
CREATE TABLE friend_relation
(
    id         VARCHAR(36) PRIMARY KEY,                       -- 关系记录ID (主键)
    user_id    VARCHAR(36) NOT NULL,                          -- 用户ID
    friend_id  VARCHAR(36) NOT NULL,                          -- 好友用户ID
    group_id   VARCHAR(64),                                   -- 所属分组ID (可为空)
    remark     VARCHAR(64)          DEFAULT '',               -- 好友备注名 (最多64字符)
    status     SMALLINT    NOT NULL DEFAULT 1,                -- 关系状态: 1-正常 2-拉黑
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 关系修改时间
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP -- 关系建立时间
);

-- 唯一约束: 防止重复添加同一好友
CREATE UNIQUE INDEX uk_user_friend ON friend_relation (user_id, friend_id);

-- 索引优化
CREATE INDEX idx_user_id ON friend_relation (user_id); -- 加速用户查询好友列表
CREATE INDEX idx_friend_id ON friend_relation (friend_id);
-- 加速反向关系查询

-- 表注释
COMMENT ON TABLE friend_relation IS '双向好友关系表';

-- 字段注释
COMMENT ON COLUMN friend_relation.user_id IS '关系所属的用户ID';
COMMENT ON COLUMN friend_relation.friend_id IS '被添加为好友的用户ID';
COMMENT ON COLUMN friend_relation.group_id IS '好友所在分组的ID (关联friend_group表)';
COMMENT ON COLUMN friend_relation.remark IS '用户为好友设置的备注名称';
COMMENT ON COLUMN friend_relation.status IS '关系状态: 1-正常好友 2-已拉黑';
COMMENT ON COLUMN friend_relation.updated_at IS '好友关系的修改时间';
COMMENT ON COLUMN friend_relation.created_at IS '好友关系的建立时间';
----------------------------250516  End----------------------------
----------------------------250521  Start----------------------------
-- 好友分组表
CREATE TABLE IF NOT EXISTS friend_group
(
    id         varchar(36) PRIMARY KEY,
    user_id    varchar(36) NOT NULL,
    group_name VARCHAR(50) NOT NULL,
    sort_order INT       DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

COMMENT ON TABLE friend_group IS '好友分组表';
COMMENT ON COLUMN friend_group.id IS '分组ID';
COMMENT ON COLUMN friend_group.user_id IS '用户ID';
COMMENT ON COLUMN friend_group.group_name IS '分组名称';
COMMENT ON COLUMN friend_group.sort_order IS '排序顺序';
COMMENT ON COLUMN friend_group.created_at IS '创建时间';
COMMENT ON COLUMN friend_group.updated_at IS '更新时间';

CREATE INDEX idx_friend_group_user_id ON friend_group (user_id);

-- 好友分组关系表
CREATE TABLE IF NOT EXISTS friend_group_relation
(
    id         varchar(36) PRIMARY KEY,
    user_id    varchar(36) NOT NULL,
    friend_id  varchar(36) NOT NULL,
    group_id   varchar(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_friend_group UNIQUE (user_id, friend_id, group_id)
    );

COMMENT ON TABLE friend_group_relation IS '好友分组关系表';
COMMENT ON COLUMN friend_group_relation.id IS '关系ID';
COMMENT ON COLUMN friend_group_relation.user_id IS '用户ID';
COMMENT ON COLUMN friend_group_relation.friend_id IS '好友ID';
COMMENT ON COLUMN friend_group_relation.group_id IS '分组ID';
COMMENT ON COLUMN friend_group_relation.created_at IS '创建时间';
COMMENT ON COLUMN friend_group_relation.updated_at IS '更新时间';
----------------------------250521  End----------------------------
----------------------------250526  Start----------------------------

----------------------------250526  End----------------------------

----------------------------250530  Start----------------------------

-- 群组设置表 (支持禁止群成员相互加好友等设置)
CREATE TABLE group_settings
(
    group_id                VARCHAR(36) PRIMARY KEY,                     -- 群组ID
    allow_member_friendship INTEGER     NOT NULL DEFAULT 1,           -- 是否允许群成员相互加好友，1-允许，0-不允许
    join_approval_required  INTEGER     NOT NULL DEFAULT 0,          -- 是否需要审批才能加入群组，1-需要，0-不需要
    only_admin_can_invite   INTEGER     NOT NULL DEFAULT 0,          -- 是否仅管理员可以邀请新成员，1-是，0-否
    only_admin_can_modify   INTEGER     NOT NULL DEFAULT 0,          -- 是否仅管理员可以修改群信息，1-是，0-否
    updated_at              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP -- 最后更新时间
);
COMMENT ON TABLE group_settings IS '群组设置表';
COMMENT ON COLUMN group_settings.group_id IS '群组ID';
COMMENT ON COLUMN group_settings.allow_member_friendship IS '是否允许群成员相互加好友，1-允许，0-不允许';
COMMENT ON COLUMN group_settings.join_approval_required IS '是否需要审批才能加入群组，1-需要，0-不需要';
COMMENT ON COLUMN group_settings.only_admin_can_invite IS '是否仅管理员可以邀请新成员，1-是，0-否';
COMMENT ON COLUMN group_settings.only_admin_can_modify IS '是否仅管理员可以修改群信息，1-是，0-否';
COMMENT ON COLUMN group_settings.updated_at IS '最后更新时间';

CREATE TRIGGER update_group_settings_modtime
    BEFORE UPDATE
    ON group_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- 群公告表
CREATE TABLE group_announcements
(
    id         VARCHAR(36) PRIMARY KEY,                              -- 公告ID
    group_id   VARCHAR(36)  NOT NULL,                                -- 群组ID
    creator_id VARCHAR(36)  NOT NULL,                                -- 创建者ID
    content    TEXT         NOT NULL,                                -- 公告内容
    title      VARCHAR(255),                                         -- 公告标题
    is_pinned  INTEGER      NOT NULL DEFAULT 0,                  -- 是否置顶，1-置顶，0-不置顶
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,      -- 创建时间
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP       -- 更新时间
);
COMMENT ON TABLE group_announcements IS '群公告表';
COMMENT ON COLUMN group_announcements.id IS '公告ID';
COMMENT ON COLUMN group_announcements.group_id IS '群组ID';
COMMENT ON COLUMN group_announcements.creator_id IS '创建者ID';
COMMENT ON COLUMN group_announcements.content IS '公告内容';
COMMENT ON COLUMN group_announcements.title IS '公告标题';
COMMENT ON COLUMN group_announcements.is_pinned IS '是否置顶，1-置顶，0-不置顶';
COMMENT ON COLUMN group_announcements.created_at IS '创建时间';
COMMENT ON COLUMN group_announcements.updated_at IS '更新时间';

CREATE INDEX idx_group_announcements_group_id ON group_announcements (group_id);
CREATE INDEX idx_group_announcements_is_pinned ON group_announcements (is_pinned);

CREATE TRIGGER update_group_announcements_modtime
    BEFORE UPDATE
    ON group_announcements
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- 群置顶聊天表
CREATE TABLE group_pinned_messages
(
    id           VARCHAR(36) PRIMARY KEY,                            -- 置顶消息ID
    group_id     VARCHAR(36) NOT NULL,                               -- 群组ID
    message_id   VARCHAR(36) NOT NULL,                               -- 消息ID
    creator_id   VARCHAR(36) NOT NULL,                               -- 创建者ID
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP      -- 创建时间
);
COMMENT ON TABLE group_pinned_messages IS '群置顶聊天表';
COMMENT ON COLUMN group_pinned_messages.id IS '置顶消息ID';
COMMENT ON COLUMN group_pinned_messages.group_id IS '群组ID';
COMMENT ON COLUMN group_pinned_messages.message_id IS '消息ID';
COMMENT ON COLUMN group_pinned_messages.creator_id IS '创建者ID';
COMMENT ON COLUMN group_pinned_messages.created_at IS '创建时间';

CREATE INDEX idx_group_pinned_messages_group_id ON group_pinned_messages (group_id);

-- 群黑名单表
CREATE TABLE group_blacklist
(
    id           VARCHAR(36) PRIMARY KEY,                            -- 黑名单记录ID
    group_id     VARCHAR(36) NOT NULL,                               -- 群组ID
    user_id      VARCHAR(36) NOT NULL,                               -- 被拉黑用户ID
    creator_id   VARCHAR(36) NOT NULL,                               -- 操作者ID
    reason       TEXT,                                               -- 拉黑理由
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,     -- 创建时间
    CONSTRAINT unique_group_blacklist UNIQUE (group_id, user_id)
);
COMMENT ON TABLE group_blacklist IS '群黑名单表';
COMMENT ON COLUMN group_blacklist.id IS '黑名单记录ID';
COMMENT ON COLUMN group_blacklist.group_id IS '群组ID';
COMMENT ON COLUMN group_blacklist.user_id IS '被拉黑用户ID';
COMMENT ON COLUMN group_blacklist.creator_id IS '操作者ID';
COMMENT ON COLUMN group_blacklist.reason IS '拉黑理由';
COMMENT ON COLUMN group_blacklist.created_at IS '创建时间';

CREATE INDEX idx_group_blacklist_group_id ON group_blacklist (group_id);
CREATE INDEX idx_group_blacklist_user_id ON group_blacklist (user_id);

-- 群禁言表
CREATE TABLE group_mutes
(
    id           VARCHAR(36) PRIMARY KEY,                            -- 禁言记录ID
    group_id     VARCHAR(36) NOT NULL,                               -- 群组ID
    user_id      VARCHAR(36) NOT NULL,                               -- 被禁言用户ID，NULL表示全员禁言
    creator_id   VARCHAR(36) NOT NULL,                               -- 操作者ID
    reason       TEXT,                                               -- 禁言理由
    mute_until   TIMESTAMP,                                          -- 禁言结束时间
    is_permanent INTEGER     NOT NULL DEFAULT 0,                 -- 是否永久禁言，1-是，0-否
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,     -- 创建时间
    updated_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,     -- 更新时间
    CONSTRAINT unique_group_mute UNIQUE (group_id, user_id)
);
COMMENT ON TABLE group_mutes IS '群禁言表';
COMMENT ON COLUMN group_mutes.id IS '禁言记录ID';
COMMENT ON COLUMN group_mutes.group_id IS '群组ID';
COMMENT ON COLUMN group_mutes.user_id IS '被禁言用户ID，NULL表示全员禁言';
COMMENT ON COLUMN group_mutes.creator_id IS '操作者ID';
COMMENT ON COLUMN group_mutes.reason IS '禁言理由';
COMMENT ON COLUMN group_mutes.mute_until IS '禁言结束时间';
COMMENT ON COLUMN group_mutes.is_permanent IS '是否永久禁言，1-是，0-否';
COMMENT ON COLUMN group_mutes.created_at IS '创建时间';
COMMENT ON COLUMN group_mutes.updated_at IS '更新时间';

CREATE INDEX idx_group_mutes_group_id ON group_mutes (group_id);
CREATE INDEX idx_group_mutes_user_id ON group_mutes (user_id);
CREATE INDEX idx_group_mutes_mute_until ON group_mutes (mute_until);

CREATE TRIGGER update_group_mutes_modtime
    BEFORE UPDATE
    ON group_mutes
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- 群邀请表
CREATE TABLE group_invitations
(
    id           VARCHAR(36) PRIMARY KEY,                            -- 邀请记录ID
    group_id     VARCHAR(36) NOT NULL,                               -- 群组ID
    inviter_id   VARCHAR(36) NOT NULL,                               -- 邀请人ID
    invitee_id   VARCHAR(36) NOT NULL,                               -- 被邀请人ID
    status       VARCHAR(10) NOT NULL DEFAULT 'PENDING',             -- 邀请状态：待处理、已接受、已拒绝
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,     -- 创建时间
    updated_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,     -- 更新时间
    CONSTRAINT check_invitation_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT unique_group_invitation UNIQUE (group_id, invitee_id)
);
COMMENT ON TABLE group_invitations IS '群邀请表';
COMMENT ON COLUMN group_invitations.id IS '邀请记录ID';
COMMENT ON COLUMN group_invitations.group_id IS '群组ID';
COMMENT ON COLUMN group_invitations.inviter_id IS '邀请人ID';
COMMENT ON COLUMN group_invitations.invitee_id IS '被邀请人ID';
COMMENT ON COLUMN group_invitations.status IS '邀请状态：待处理、已接受、已拒绝';
COMMENT ON COLUMN group_invitations.created_at IS '创建时间';
COMMENT ON COLUMN group_invitations.updated_at IS '更新时间';

CREATE INDEX idx_group_invitations_group_id ON group_invitations (group_id);
CREATE INDEX idx_group_invitations_invitee_id ON group_invitations (invitee_id);
CREATE INDEX idx_group_invitations_status ON group_invitations (status);

CREATE TRIGGER update_group_invitations_modtime
    BEFORE UPDATE
    ON group_invitations
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- 群二维码表
CREATE TABLE group_qrcodes
(
    id           VARCHAR(36) PRIMARY KEY,                            -- 二维码ID
    group_id     VARCHAR(36)  NOT NULL,                              -- 群组ID
    creator_id   VARCHAR(36)  NOT NULL,                              -- 创建者ID
    qrcode_url   VARCHAR(255) NOT NULL,                              -- 二维码URL
    expires_at   TIMESTAMP,                                          -- 过期时间，NULL表示永不过期
    is_permanent INTEGER      NOT NULL DEFAULT 0,                -- 是否永久有效，1-是，0-否
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP     -- 创建时间
);
COMMENT ON TABLE group_qrcodes IS '群二维码表';
COMMENT ON COLUMN group_qrcodes.id IS '二维码ID';
COMMENT ON COLUMN group_qrcodes.group_id IS '群组ID';
COMMENT ON COLUMN group_qrcodes.creator_id IS '创建者ID';
COMMENT ON COLUMN group_qrcodes.qrcode_url IS '二维码URL';
COMMENT ON COLUMN group_qrcodes.expires_at IS '过期时间，NULL表示永不过期';
COMMENT ON COLUMN group_qrcodes.is_permanent IS '是否永久有效，1-是，0-否';
COMMENT ON COLUMN group_qrcodes.created_at IS '创建时间';

CREATE INDEX idx_group_qrcodes_group_id ON group_qrcodes (group_id);

-- 群成员免打扰设置
CREATE TABLE group_member_settings
(
    id                 VARCHAR(36) PRIMARY KEY,                      -- 设置ID
    group_id           VARCHAR(36) NOT NULL,                         -- 群组ID
    user_id            VARCHAR(36) NOT NULL,                         -- 用户ID
    mute_notifications INTEGER     NOT NULL DEFAULT 0,           -- 是否免打扰，1-是，0-否
    nickname_in_group  VARCHAR(50),                                  -- 在群内的昵称
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 创建时间
    updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新时间
    CONSTRAINT unique_member_settings UNIQUE (group_id, user_id)
);
COMMENT ON TABLE group_member_settings IS '群成员设置表';
COMMENT ON COLUMN group_member_settings.id IS '设置ID';
COMMENT ON COLUMN group_member_settings.group_id IS '群组ID';
COMMENT ON COLUMN group_member_settings.user_id IS '用户ID';
COMMENT ON COLUMN group_member_settings.mute_notifications IS '是否免打扰，1-是，0-否';
COMMENT ON COLUMN group_member_settings.nickname_in_group IS '在群内的昵称';
COMMENT ON COLUMN group_member_settings.created_at IS '创建时间';
COMMENT ON COLUMN group_member_settings.updated_at IS '更新时间';

CREATE INDEX idx_group_member_settings_group_id ON group_member_settings (group_id);
CREATE INDEX idx_group_member_settings_user_id ON group_member_settings (user_id);
CREATE INDEX idx_group_member_settings_user_group ON group_member_settings(user_id, group_id);

CREATE TRIGGER update_group_member_settings_modtime
    BEFORE UPDATE
    ON group_member_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- 为user_config表添加声音和震动开关字段
ALTER TABLE "user_config" ADD COLUMN "sound_enabled" int4 DEFAULT 2;
ALTER TABLE "user_config" ADD COLUMN "vibration_enabled" int4 DEFAULT 2;

COMMENT ON COLUMN "user_config"."sound_enabled" IS '是否开启声音(1-是，2-否)';
COMMENT ON COLUMN "user_config"."vibration_enabled" IS '是否开启震动(1-是，2-否)';


-- 功能: 添加用户黑名单表和相关功能

-- 创建用户黑名单表
CREATE TABLE IF NOT EXISTS user_blacklist (
                                              id VARCHAR(36) PRIMARY KEY,                          -- 黑名单记录ID
    user_id VARCHAR(36) NOT NULL,                        -- 用户ID（拉黑操作的发起者）
    blocked_user_id VARCHAR(36) NOT NULL,                -- 被拉黑用户ID
    reason VARCHAR(255),                                 -- 拉黑原因(可选)
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 创建时间
    CONSTRAINT uk_user_blocked_user UNIQUE (user_id, blocked_user_id)
    );

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_user_blacklist_user_id ON user_blacklist (user_id);
CREATE INDEX IF NOT EXISTS idx_user_blacklist_blocked_user_id ON user_blacklist (blocked_user_id);

-- 添加表和字段注释
COMMENT ON TABLE user_blacklist IS '用户黑名单表';
COMMENT ON COLUMN user_blacklist.id IS '黑名单记录ID';
COMMENT ON COLUMN user_blacklist.user_id IS '拉黑操作的发起者ID';
COMMENT ON COLUMN user_blacklist.blocked_user_id IS '被拉黑用户ID';
COMMENT ON COLUMN user_blacklist.reason IS '拉黑原因';
COMMENT ON COLUMN user_blacklist.created_at IS '拉黑时间';

----------------------------250530  End----------------------------
----------------------------250531  Start----------------------------



----------------------------250531  End----------------------------
