-- 初始化DDL文件，由各个版本合并生成
-- 包含所有需要创建的表和结构，但不包括修改操作

-- 触发器函数，用于自动更新updated_at字段
CREATE OR REPLACE FUNCTION update_modified_column()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

-- 用户表
CREATE TABLE users
(
    id               varchar(36)    NOT NULL,
    username         varchar(36),
    email            varchar(100),
    password         varchar(128)   NOT NULL,
    nickname         varchar(50),
    avatar_url       varchar(1000),
    created_at       timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       timestamptz(6),
    phone            varchar(36)    NOT NULL,
    address          varchar(255),
    head_image       varchar(255),
    head_image_thumb varchar(255),
    sex              int4,
    user_stat        int4                    DEFAULT 1,
    tenant_id        varchar(20),
    last_login_time  timestamptz(6),
    custom_id        varchar(20)    NOT NULL,
    sign             varchar(100),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT unique_custom_id UNIQUE (custom_id)
);

COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.id IS '用户ID';
COMMENT ON COLUMN users.username IS '用户名';
COMMENT ON COLUMN users.email IS '邮箱';
COMMENT ON COLUMN users.password IS '密码';
COMMENT ON COLUMN users.nickname IS '昵称';
COMMENT ON COLUMN users.created_at IS '创建时间';
COMMENT ON COLUMN users.updated_at IS '修改时间';
COMMENT ON COLUMN users.phone IS '手机号';
COMMENT ON COLUMN users.address IS '地址';
COMMENT ON COLUMN users.head_image IS '用户头像';
COMMENT ON COLUMN users.head_image_thumb IS '用户头像缩略图';
COMMENT ON COLUMN users.sex IS '性别 1:男 2:女';
COMMENT ON COLUMN users.user_stat IS '用户状态(1-正常，2-已删除 3-已注销)';
COMMENT ON COLUMN users.tenant_id IS '企业号';
COMMENT ON COLUMN users.last_login_time IS '最后登录时间';
COMMENT ON COLUMN users.custom_id IS '用户自定义ID';
COMMENT ON COLUMN users.sign IS '用户个性签名';
COMMENT ON COLUMN users.avatar_url IS '用户头像URL';

-- 创建触发器自动更新users表的updated_at
CREATE TRIGGER update_users_modtime
    BEFORE UPDATE
    ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- 用户设置表
CREATE TABLE user_config
(
    id                 int4 GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    user_id            varchar(36)                                                                        NOT NULL,
    allow_phone_search int4           DEFAULT 1,
    allow_id_search    int4           DEFAULT 1,
    auto_load_video    int4           DEFAULT 2,
    auto_load_pic      int4           DEFAULT 2,
    msg_read_flag      int4           DEFAULT 1,
    create_time        timestamptz(6) DEFAULT CURRENT_TIMESTAMP,
    update_time        timestamptz(6),
    show_phone         int4           DEFAULT 2,
    sound_enabled      int4           DEFAULT 1,
    vibration_enabled  int4           DEFAULT 2
);

COMMENT ON TABLE user_config IS '用户设置表';
COMMENT ON COLUMN user_config.id IS '主键';
COMMENT ON COLUMN user_config.user_id IS '用户ID';
COMMENT ON COLUMN user_config.allow_phone_search IS '是否允许手机搜索(1-是，2-否)';
COMMENT ON COLUMN user_config.allow_id_search IS '是否允许ID搜索(1-是，2-否)';
COMMENT ON COLUMN user_config.auto_load_video IS '是否自动缓存视频(1-是，2-否)';
COMMENT ON COLUMN user_config.auto_load_pic IS '是否自动加载图片(1-是，2-否)';
COMMENT ON COLUMN user_config.msg_read_flag IS '是否已读回执(1-是，2-否)';
COMMENT ON COLUMN user_config.create_time IS '创建时间';
COMMENT ON COLUMN user_config.update_time IS '修改时间';
COMMENT ON COLUMN user_config.show_phone IS '是否展示手机号(1-是，2-否)';
COMMENT ON COLUMN user_config.sound_enabled IS '是否开启声音(1-是，2-否)';
COMMENT ON COLUMN user_config.vibration_enabled IS '是否开启震动(1-是，2-否)';

-- 好友关系表
CREATE TABLE friendships
(
    id            VARCHAR(36) PRIMARY KEY,
    user_id       VARCHAR(36) NOT NULL,
    friend_id     VARCHAR(36) NOT NULL,
    status        VARCHAR(10) NOT NULL DEFAULT '0',
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message       VARCHAR(255)         DEFAULT '',
    reject_reason VARCHAR(255),
    CONSTRAINT check_status CHECK (status IN ('0', '1', '2', '3')),
    CONSTRAINT unique_friendship UNIQUE (user_id, friend_id)
);

CREATE INDEX idx_friendships_user_id ON friendships (user_id);
CREATE INDEX idx_friendships_friend_id ON friendships (friend_id);
CREATE INDEX idx_friendships_status ON friendships (status);

-- 创建触发器自动更新friendships表的updated_at
CREATE TRIGGER update_friendships_modtime
    BEFORE UPDATE
    ON friendships
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

COMMENT ON COLUMN friendships.reject_reason IS '好友请求拒绝理由';

-- 双向好友关系表
CREATE TABLE friend_relation
(
    id         VARCHAR(36) PRIMARY KEY,
    user_id    VARCHAR(36) NOT NULL,
    friend_id  VARCHAR(36) NOT NULL,
    group_id   VARCHAR(64),
    remark     VARCHAR(64)          DEFAULT '',
    status     SMALLINT    NOT NULL DEFAULT 1,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    friend_type SMALLINT   NOT NULL DEFAULT 0,
    is_starred SMALLINT    NOT NULL DEFAULT 0,
    is_top     SMALLINT    NOT NULL DEFAULT 0
);

-- 唯一约束: 防止重复添加同一好友
CREATE UNIQUE INDEX uk_user_friend ON friend_relation (user_id, friend_id);

-- 索引优化
CREATE INDEX idx_user_id ON friend_relation (user_id);
CREATE INDEX idx_friend_id ON friend_relation (friend_id);
CREATE INDEX idx_friend_relation_star_top ON friend_relation (is_starred, is_top);

COMMENT ON TABLE friend_relation IS '双向好友关系表';
COMMENT ON COLUMN friend_relation.user_id IS '关系所属的用户ID';
COMMENT ON COLUMN friend_relation.friend_id IS '被添加为好友的用户ID';
COMMENT ON COLUMN friend_relation.group_id IS '好友所在分组的ID (关联friend_group表)';
COMMENT ON COLUMN friend_relation.remark IS '用户为好友设置的备注名称';
COMMENT ON COLUMN friend_relation.status IS '关系状态: 1-正常好友 2-已拉黑';
COMMENT ON COLUMN friend_relation.updated_at IS '好友关系的修改时间';
COMMENT ON COLUMN friend_relation.created_at IS '好友关系的建立时间';
COMMENT ON COLUMN friend_relation.friend_type IS '好友类型: 0-普通好友 1-官方账号 2-系统账号';
COMMENT ON COLUMN friend_relation.is_starred IS '是否星标好友: 0-不是星标 1-是星标';
COMMENT ON COLUMN friend_relation.is_top IS '是否置顶好友: 0-不是置顶 1-是置顶';

-- 好友分组表
CREATE TABLE friend_group
(
    id         varchar(36) PRIMARY KEY,
    user_id    varchar(36) NOT NULL,
    group_name VARCHAR(50) NOT NULL,
    sort_order INT       DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE friend_group IS '好友分组表';
COMMENT ON COLUMN friend_group.id IS '分组ID';
COMMENT ON COLUMN friend_group.user_id IS '用户ID';
COMMENT ON COLUMN friend_group.group_name IS '分组名称';
COMMENT ON COLUMN friend_group.sort_order IS '排序顺序';
COMMENT ON COLUMN friend_group.created_at IS '创建时间';
COMMENT ON COLUMN friend_group.updated_at IS '更新时间';

CREATE INDEX idx_friend_group_user_id ON friend_group (user_id);

-- 好友分组关系表
CREATE TABLE friend_group_relation
(
    id         varchar(36) PRIMARY KEY,
    user_id    varchar(36) NOT NULL,
    friend_id  varchar(36) NOT NULL,
    group_id   varchar(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_friend_group UNIQUE (user_id, friend_id, group_id)
);

COMMENT ON TABLE friend_group_relation IS '好友分组关系表';
COMMENT ON COLUMN friend_group_relation.id IS '关系ID';
COMMENT ON COLUMN friend_group_relation.user_id IS '用户ID';
COMMENT ON COLUMN friend_group_relation.friend_id IS '好友ID';
COMMENT ON COLUMN friend_group_relation.group_id IS '分组ID';
COMMENT ON COLUMN friend_group_relation.created_at IS '创建时间';
COMMENT ON COLUMN friend_group_relation.updated_at IS '更新时间';

-- 用户黑名单表
CREATE TABLE user_blacklist (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    blocked_user_id VARCHAR(36) NOT NULL,
    reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_blocked_user UNIQUE (user_id, blocked_user_id)
);

CREATE INDEX idx_user_blacklist_user_id ON user_blacklist (user_id);
CREATE INDEX idx_user_blacklist_blocked_user_id ON user_blacklist (blocked_user_id);

COMMENT ON TABLE user_blacklist IS '用户黑名单表';
COMMENT ON COLUMN user_blacklist.id IS '黑名单记录ID';
COMMENT ON COLUMN user_blacklist.user_id IS '拉黑操作的发起者ID';
COMMENT ON COLUMN user_blacklist.blocked_user_id IS '被拉黑用户ID';
COMMENT ON COLUMN user_blacklist.reason IS '拉黑原因';
COMMENT ON COLUMN user_blacklist.created_at IS '拉黑时间';

-- 群组表
CREATE TABLE groups
(
    id              VARCHAR(36) PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    description     TEXT,
    avatar_url      VARCHAR(255),
    owner_id        VARCHAR(36)  NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    max_members     INTEGER      NOT NULL DEFAULT 500,
    announcement_id VARCHAR(36),
    join_mode       VARCHAR(10)  NOT NULL DEFAULT 'APPROVAL' CHECK (join_mode IN ('OPEN', 'APPROVAL', 'INVITE_ONLY')),
    qrcode_id       VARCHAR(36),
    group_type      VARCHAR(10)  NOT NULL DEFAULT 'NORMAL' CHECK (group_type IN ('NORMAL', 'SUPER'))
);

CREATE INDEX idx_groups_owner_id ON groups (owner_id);
CREATE INDEX idx_groups_name ON groups (name);

-- 创建触发器自动更新groups表的updated_at
CREATE TRIGGER update_groups_modtime
    BEFORE UPDATE
    ON groups
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

COMMENT ON TABLE groups IS '群组表';
COMMENT ON COLUMN groups.id IS '群组ID';
COMMENT ON COLUMN groups.name IS '群组名称';
COMMENT ON COLUMN groups.description IS '群组描述';
COMMENT ON COLUMN groups.avatar_url IS '群组头像URL';
COMMENT ON COLUMN groups.owner_id IS '群主ID';
COMMENT ON COLUMN groups.created_at IS '创建时间';
COMMENT ON COLUMN groups.updated_at IS '更新时间';
COMMENT ON COLUMN groups.max_members IS '群组最大成员数量，默认500人';
COMMENT ON COLUMN groups.announcement_id IS '当前群公告ID';
COMMENT ON COLUMN groups.join_mode IS '加入模式：OPEN(开放)、APPROVAL(审批)、INVITE_ONLY(仅邀请)';
COMMENT ON COLUMN groups.qrcode_id IS '当前群二维码ID';
COMMENT ON COLUMN groups.group_type IS '群类型：NORMAL(普通群)、SUPER(超级群/大群)';

-- 群组成员表
CREATE TABLE group_members
(
    id        VARCHAR(36) PRIMARY KEY,
    group_id  VARCHAR(36) NOT NULL,
    user_id   VARCHAR(36) NOT NULL,
    role      VARCHAR(10) NOT NULL,
    joined_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_membership UNIQUE (group_id, user_id)
);

CREATE INDEX idx_group_members_group_id ON group_members (group_id);
CREATE INDEX idx_group_members_user_id ON group_members (user_id);

COMMENT ON TABLE group_members IS '群组成员表';
COMMENT ON COLUMN group_members.id IS '成员记录ID';
COMMENT ON COLUMN group_members.group_id IS '群组ID';
COMMENT ON COLUMN group_members.user_id IS '用户ID';
COMMENT ON COLUMN group_members.role IS '角色：0：MEMBER(普通成员)、1：ADMIN(管理员)、2：OWNER(群主)';
COMMENT ON COLUMN group_members.joined_at IS '加入时间';

-- 群组设置表
CREATE TABLE group_settings
(
    group_id                VARCHAR(36) PRIMARY KEY,
    allow_member_friendship INTEGER     NOT NULL DEFAULT 1,
    join_approval_required  INTEGER     NOT NULL DEFAULT 0,
    only_admin_can_invite   INTEGER     NOT NULL DEFAULT 0,
    only_admin_can_modify   INTEGER     NOT NULL DEFAULT 0,
    updated_at              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notify_member_join      INTEGER     NOT NULL DEFAULT 1,
    all_member_muted        INTEGER     NOT NULL DEFAULT 0
);

CREATE TRIGGER update_group_settings_modtime
    BEFORE UPDATE
    ON group_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

COMMENT ON TABLE group_settings IS '群组设置表';
COMMENT ON COLUMN group_settings.group_id IS '群组ID';
COMMENT ON COLUMN group_settings.allow_member_friendship IS '是否允许群成员相互加好友，1-允许，0-不允许';
COMMENT ON COLUMN group_settings.join_approval_required IS '是否需要审批才能加入群组，1-需要，0-不需要';
COMMENT ON COLUMN group_settings.only_admin_can_invite IS '是否仅管理员可以邀请新成员，1-是，0-否';
COMMENT ON COLUMN group_settings.only_admin_can_modify IS '是否仅管理员可以修改群信息，1-是，0-否';
COMMENT ON COLUMN group_settings.updated_at IS '最后更新时间';
COMMENT ON COLUMN group_settings.notify_member_join IS '是否开启群成员进群提醒，1-开启，0-关闭';
COMMENT ON COLUMN group_settings.all_member_muted IS '是否开启全员禁言，1-开启，0-关闭';

-- 群公告表
CREATE TABLE group_announcements
(
    id         VARCHAR(36) PRIMARY KEY,
    group_id   VARCHAR(36)  NOT NULL,
    creator_id VARCHAR(36)  NOT NULL,
    content    TEXT         NOT NULL,
    title      VARCHAR(255),
    is_pinned  INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_group_announcements_group_id ON group_announcements (group_id);
CREATE INDEX idx_group_announcements_is_pinned ON group_announcements (is_pinned);

CREATE TRIGGER update_group_announcements_modtime
    BEFORE UPDATE
    ON group_announcements
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

COMMENT ON TABLE group_announcements IS '群公告表';
COMMENT ON COLUMN group_announcements.id IS '公告ID';
COMMENT ON COLUMN group_announcements.group_id IS '群组ID';
COMMENT ON COLUMN group_announcements.creator_id IS '创建者ID';
COMMENT ON COLUMN group_announcements.content IS '公告内容';
COMMENT ON COLUMN group_announcements.title IS '公告标题';
COMMENT ON COLUMN group_announcements.is_pinned IS '是否置顶，1-置顶，0-不置顶';
COMMENT ON COLUMN group_announcements.created_at IS '创建时间';
COMMENT ON COLUMN group_announcements.updated_at IS '更新时间';

-- 群置顶聊天表
CREATE TABLE group_pinned_messages
(
    id           VARCHAR(36) PRIMARY KEY,
    group_id     VARCHAR(36) NOT NULL,
    message_id   VARCHAR(36) NOT NULL,
    creator_id   VARCHAR(36) NOT NULL,
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_group_pinned_messages_group_id ON group_pinned_messages (group_id);

COMMENT ON TABLE group_pinned_messages IS '群置顶聊天表';
COMMENT ON COLUMN group_pinned_messages.id IS '置顶消息ID';
COMMENT ON COLUMN group_pinned_messages.group_id IS '群组ID';
COMMENT ON COLUMN group_pinned_messages.message_id IS '消息ID';
COMMENT ON COLUMN group_pinned_messages.creator_id IS '创建者ID';
COMMENT ON COLUMN group_pinned_messages.created_at IS '创建时间';

-- 群黑名单表
CREATE TABLE group_blacklist
(
    id           VARCHAR(36) PRIMARY KEY,
    group_id     VARCHAR(36) NOT NULL,
    user_id      VARCHAR(36) NOT NULL,
    creator_id   VARCHAR(36) NOT NULL,
    reason       TEXT,
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_group_blacklist UNIQUE (group_id, user_id)
);

CREATE INDEX idx_group_blacklist_group_id ON group_blacklist (group_id);
CREATE INDEX idx_group_blacklist_user_id ON group_blacklist (user_id);

COMMENT ON TABLE group_blacklist IS '群黑名单表';
COMMENT ON COLUMN group_blacklist.id IS '黑名单记录ID';
COMMENT ON COLUMN group_blacklist.group_id IS '群组ID';
COMMENT ON COLUMN group_blacklist.user_id IS '被拉黑用户ID';
COMMENT ON COLUMN group_blacklist.creator_id IS '操作者ID';
COMMENT ON COLUMN group_blacklist.reason IS '拉黑理由';
COMMENT ON COLUMN group_blacklist.created_at IS '创建时间';

-- 群禁言表
CREATE TABLE group_mutes
(
    id           VARCHAR(36) PRIMARY KEY,
    group_id     VARCHAR(36) NOT NULL,
    user_id      VARCHAR(36) NOT NULL,
    creator_id   VARCHAR(36) NOT NULL,
    reason       TEXT,
    mute_until   TIMESTAMP,
    is_permanent INTEGER     NOT NULL DEFAULT 0,
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_group_mute UNIQUE (group_id, user_id)
);

CREATE INDEX idx_group_mutes_group_id ON group_mutes (group_id);
CREATE INDEX idx_group_mutes_user_id ON group_mutes (user_id);
CREATE INDEX idx_group_mutes_mute_until ON group_mutes (mute_until);

CREATE TRIGGER update_group_mutes_modtime
    BEFORE UPDATE
    ON group_mutes
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

COMMENT ON TABLE group_mutes IS '群禁言表';
COMMENT ON COLUMN group_mutes.id IS '禁言记录ID';
COMMENT ON COLUMN group_mutes.group_id IS '群组ID';
COMMENT ON COLUMN group_mutes.user_id IS '被禁言用户ID，NULL表示全员禁言';
COMMENT ON COLUMN group_mutes.creator_id IS '操作者ID';
COMMENT ON COLUMN group_mutes.reason IS '禁言理由';
COMMENT ON COLUMN group_mutes.mute_until IS '禁言结束时间';
COMMENT ON COLUMN group_mutes.is_permanent IS '是否永久禁言，1-是，0-否';
COMMENT ON COLUMN group_mutes.created_at IS '创建时间';
COMMENT ON COLUMN group_mutes.updated_at IS '更新时间';

-- 群邀请表
CREATE TABLE group_invitations
(
    id           VARCHAR(36) PRIMARY KEY,
    group_id     VARCHAR(36) NOT NULL,
    inviter_id   VARCHAR(36) NOT NULL,
    invitee_id   VARCHAR(36) NOT NULL,
    status       VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_invitation_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT unique_group_invitation UNIQUE (group_id, invitee_id)
);

CREATE INDEX idx_group_invitations_group_id ON group_invitations (group_id);
CREATE INDEX idx_group_invitations_invitee_id ON group_invitations (invitee_id);
CREATE INDEX idx_group_invitations_status ON group_invitations (status);

CREATE TRIGGER update_group_invitations_modtime
    BEFORE UPDATE
    ON group_invitations
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

COMMENT ON TABLE group_invitations IS '群邀请表';
COMMENT ON COLUMN group_invitations.id IS '邀请记录ID';
COMMENT ON COLUMN group_invitations.group_id IS '群组ID';
COMMENT ON COLUMN group_invitations.inviter_id IS '邀请人ID';
COMMENT ON COLUMN group_invitations.invitee_id IS '被邀请人ID';
COMMENT ON COLUMN group_invitations.status IS '邀请状态：待处理、已接受、已拒绝';
COMMENT ON COLUMN group_invitations.created_at IS '创建时间';
COMMENT ON COLUMN group_invitations.updated_at IS '更新时间';

-- 群二维码表
CREATE TABLE group_qrcodes
(
    id           VARCHAR(36) PRIMARY KEY,
    group_id     VARCHAR(36)  NOT NULL,
    creator_id   VARCHAR(36)  NOT NULL,
    qrcode_url   VARCHAR(255) NOT NULL,
    expires_at   TIMESTAMP,
    is_permanent INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_group_qrcodes_group_id ON group_qrcodes (group_id);

COMMENT ON TABLE group_qrcodes IS '群二维码表';
COMMENT ON COLUMN group_qrcodes.id IS '二维码ID';
COMMENT ON COLUMN group_qrcodes.group_id IS '群组ID';
COMMENT ON COLUMN group_qrcodes.creator_id IS '创建者ID';
COMMENT ON COLUMN group_qrcodes.qrcode_url IS '二维码URL';
COMMENT ON COLUMN group_qrcodes.expires_at IS '过期时间，NULL表示永不过期';
COMMENT ON COLUMN group_qrcodes.is_permanent IS '是否永久有效，1-是，0-否';
COMMENT ON COLUMN group_qrcodes.created_at IS '创建时间';

-- 群成员设置表
CREATE TABLE group_member_settings
(
    id                  VARCHAR(36) PRIMARY KEY,
    group_id            VARCHAR(36) NOT NULL,
    user_id             VARCHAR(36) NOT NULL,
    mute_notifications  INTEGER     NOT NULL DEFAULT 0,
    nickname_in_group   VARCHAR(50),
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark              VARCHAR(255),
    is_top              INTEGER     NOT NULL DEFAULT 0,
    recall_notification INTEGER     NOT NULL DEFAULT 0,
    show_nickname       INTEGER     NOT NULL DEFAULT 1,
    CONSTRAINT unique_member_settings UNIQUE (group_id, user_id)
);

CREATE INDEX idx_group_member_settings_group_id ON group_member_settings (group_id);
CREATE INDEX idx_group_member_settings_user_id ON group_member_settings (user_id);
CREATE INDEX idx_group_member_settings_user_group ON group_member_settings(user_id, group_id);

CREATE TRIGGER update_group_member_settings_modtime
    BEFORE UPDATE
    ON group_member_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

COMMENT ON TABLE group_member_settings IS '群成员设置表';
COMMENT ON COLUMN group_member_settings.id IS '设置ID';
COMMENT ON COLUMN group_member_settings.group_id IS '群组ID';
COMMENT ON COLUMN group_member_settings.user_id IS '用户ID';
COMMENT ON COLUMN group_member_settings.mute_notifications IS '是否免打扰，1-是，0-否';
COMMENT ON COLUMN group_member_settings.nickname_in_group IS '在群内的昵称';
COMMENT ON COLUMN group_member_settings.created_at IS '创建时间';
COMMENT ON COLUMN group_member_settings.updated_at IS '更新时间';
COMMENT ON COLUMN group_member_settings.remark IS '群备注';
COMMENT ON COLUMN group_member_settings.is_top IS '群置顶，1-是，0-否';
COMMENT ON COLUMN group_member_settings.recall_notification IS '群撤回通知，1-是，0-否';
COMMENT ON COLUMN group_member_settings.show_nickname IS '是否显示群昵称，1-是，0-否';
